---
kind: pipeline
name: build-and-deploy

platform:
  os: linux
  arch: amd64

steps:
  - name: clone-drone-repo
    image: docker:git
    commands:
      - git clone --recursive https://github.com/drone/drone.git drone
      - (cd drone && git checkout $(cat ../VERSION))
  - name: apply-patch
    image: alpine:3.11
    commands:
      - patch drone/docker/Dockerfile.server.linux.amd64 < Dockerfile.server.linux.amd64.patch
  - name: build-drone-oss
    image: golang:1.14
    commands:
      - (cd drone && ../build.sh)
      - (cd drone && ../tags.sh) > .tags
    environment:
      CGO_ENABLED: 1
      GO111MODULE: on
      GOARCH: amd64
      GOOS: linux
      GOPROXY: https://proxy.golang.org,direct
  - name: build-standard-image
    image: plugins/docker
    settings:
      context: drone
      dockerfile: drone/docker/Dockerfile.server.linux.amd64
      password:
        from_secret: docker_password
      repo: garykim/drone-oss
      username: garykim
    when:
      branch:
        - master
      event:
        - push
      repo:
        - gary-kim/drone-oss

trigger:
  branch:
    - master
  event:
    - pull_request
    - push

---
kind: pipeline
name: personal-drone-nolimit

platform:
  os: linux
  arch: amd64

steps:
  - name: clone-drone-repo
    image: docker:git
    commands:
      - git clone --recursive https://github.com/drone/drone.git drone
      - (cd drone && git checkout $(cat ../VERSION))
  - name: apply-patch
    image: alpine:3.11
    commands:
      - patch drone/docker/Dockerfile.server.linux.amd64 < Dockerfile.server.linux.amd64.patch
  - name: build-drone-nolimit
    image: golang:1.14
    commands:
      - (cd drone && ../build.sh nolimit)
      - (cd drone && ../tags.sh) > .tags
    environment:
      CGO_ENABLED: 1
      GO111MODULE: on
      GOARCH: amd64
      GOOS: linux
      GOPROXY: https://proxy.golang.org,direct
  - name: build-nolimit-image
    image: plugins/docker
    settings:
      context: drone
      dockerfile: drone/docker/Dockerfile.server.linux.amd64
      password:
        from_secret: docker_password
      repo: garykim/drone-nolimit
      username: garykim
    when:
      branch:
        - master
      event:
        - push
      repo:
        - gary-kim/drone-oss

trigger:
  branch:
    - master
  event:
    - pull_request
    - push
