--- drone/docker/Dockerfile.server.linux.amd64	2019-12-31 15:10:00.660637916 +0800
+++ drone/docker/Dockerfile.server.linux.amd64.1	2019-12-31 15:10:08.971805311 +0800
@@ -19,6 +19,7 @@
 ENV DRONE_SERVER_HOST=localhost
 ENV DRONE_DATADOG_ENABLED=true
 ENV DRONE_DATADOG_ENDPOINT=https://stats.drone.ci/api/v1/series
+ENV DRONE_AGENTS_DISABLED=true
 
 COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 
