--- drone/docker/Dockerfile.server.linux.amd64
+++ drone/docker/Dockerfile.server.linux.amd64.1
@@ -19,9 +19,10 @@ ENV DRONE_SERVER_PORT=:80
 ENV DRONE_SERVER_HOST=localhost
 ENV DRONE_DATADOG_ENABLED=true
 ENV DRONE_DATADOG_ENDPOINT=https://stats.drone.ci/api/v1/series
+ENV DRONE_AGENTS_DISABLED=true
 
 COPY --from=alpine /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
 COPY --from=alpine /usr/share/zoneinfo /usr/share/zoneinfo
 
 ADD release/linux/amd64/drone-server /bin/
-ENTRYPOINT ["/bin/drone-server"]
\ No newline at end of file
+ENTRYPOINT ["/bin/drone-server"]
